server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: spring-boot-rest-api

  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
    pool:
      enabled: true

  h2:
    console:
      enabled: true

# Env variables
deacero-properties:
  some-property: some-value

# Enable configuration for springdoc-openapi (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
